import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Menu from "@/components/Menu";
import { fetchMenu } from "@/lib/drupalClient";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch main menu
  let mainMenu: any[] = [];
  try {
    const menuData = await fetchMenu();
    // Ensure we have a valid array
    mainMenu = Array.isArray(menuData) ? menuData : [];
  } catch (error) {
    console.error('Failed to fetch main menu:', error);
    // Continue rendering without menu on error
    mainMenu = [];
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-gray-900`}
      >
        <header className="bg-white border-b border-gray-200">
          <div className="container mx-auto px-4">
            <nav className="flex items-center h-16">
              {mainMenu.length > 0 && (
                <Menu
                  items={mainMenu}
                  className="flex items-center space-x-8"
                  itemClassName=""
                />
              )}
            </nav>
          </div>
        </header>
        <main className="container mx-auto px-4 py-8 bg-white min-h-screen">
          {children}
        </main>
        <footer className="bg-gray-50 border-t border-gray-200 mt-12">
          <div className="container mx-auto px-4 py-6 text-center text-gray-600 text-sm">
            <p>Powered by Lupus Decoupled Next.js Demo</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
